[webservers]web-1 ansible_host=10.129.0.30 fqdn=epdscpuhiqfta4f51bgt.auto.internalweb-2 ansible_host=10.129.0.33 fqdn=epdl40g78lcpi10upgo8.auto.internal
[databases]main ansible_host=10.129.0.20 fqdn=epdkq1mntqh1h2ln7rjc.auto.internalreplica ansible_host=10.129.0.16 fqdn=epd86oppok684hs8r7ui.auto.internal
[storage]
storage ansible_host=10.129.0.21 fqdn=epd0tgja6066t1mdhbub.auto.internal
